/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author GIA BAO
 */
public class DataInput extends javax.swing.JPanel {

    /**
     * Creates new form DataInput
     */
    public DataInput() {
        initComponents();
        this.setSize(50, 20);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLbl = new javax.swing.JLabel();
        valueInput = new javax.swing.JSpinner();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(31, 92, 169)));

        nameLbl.setFont(new java.awt.Font("K2D", 1, 12)); // NOI18N
        nameLbl.setText("Giá trị 1 = ");

        valueInput.setFont(new java.awt.Font("K2D", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(valueInput, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(nameLbl)
                .addContainerGap(15, Short.MAX_VALUE))
            .addComponent(valueInput)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    public int getData() throws NumberFormatException{
        return Integer.parseInt(String.valueOf(valueInput.getModel().getValue()));
    }

    public void setDataIdx(int index){
        nameLbl.setText("Giá trị " + index);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel nameLbl;
    private javax.swing.JSpinner valueInput;
    // End of variables declaration//GEN-END:variables
}
